/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * BatchUpdateUnitsBody
 */
@JsonPropertyOrder({
  BatchUpdateUnitsBody.JSON_PROPERTY_IDS,
  BatchUpdateUnitsBody.JSON_PROPERTY_PATCH_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T18:57:29.273682275Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class BatchUpdateUnitsBody {
  public static final String JSON_PROPERTY_IDS = "ids";
  @javax.annotation.Nonnull
  private List<String> ids = new ArrayList<>();

  public static final String JSON_PROPERTY_PATCH_DATA = "patchData";
  @javax.annotation.Nonnull
  private Map<String, Object> patchData = new HashMap<>();

  public BatchUpdateUnitsBody() { 
  }

  public BatchUpdateUnitsBody ids(@javax.annotation.Nonnull List<String> ids) {
    this.ids = ids;
    return this;
  }

  public BatchUpdateUnitsBody addIdsItem(String idsItem) {
    if (this.ids == null) {
      this.ids = new ArrayList<>();
    }
    this.ids.add(idsItem);
    return this;
  }

  /**
   * Get ids
   * @return ids
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getIds() {
    return ids;
  }


  @JsonProperty(value = JSON_PROPERTY_IDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIds(@javax.annotation.Nonnull List<String> ids) {
    this.ids = ids;
  }


  public BatchUpdateUnitsBody patchData(@javax.annotation.Nonnull Map<String, Object> patchData) {
    this.patchData = patchData;
    return this;
  }

  public BatchUpdateUnitsBody putPatchDataItem(String key, Object patchDataItem) {
    if (this.patchData == null) {
      this.patchData = new HashMap<>();
    }
    this.patchData.put(key, patchDataItem);
    return this;
  }

  /**
   * Get patchData
   * @return patchData
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATCH_DATA, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getPatchData() {
    return patchData;
  }


  @JsonProperty(value = JSON_PROPERTY_PATCH_DATA, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setPatchData(@javax.annotation.Nonnull Map<String, Object> patchData) {
    this.patchData = patchData;
  }


  /**
   * Return true if this BatchUpdateUnitsBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchUpdateUnitsBody batchUpdateUnitsBody = (BatchUpdateUnitsBody) o;
    return Objects.equals(this.ids, batchUpdateUnitsBody.ids) &&
        Objects.equals(this.patchData, batchUpdateUnitsBody.patchData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ids, patchData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchUpdateUnitsBody {\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    patchData: ").append(toIndentedString(patchData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `ids` to the URL query string
    if (getIds() != null) {
      for (int i = 0; i < getIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getIds().get(i)))));
      }
    }

    // add `patchData` to the URL query string
    if (getPatchData() != null) {
      for (String _key : getPatchData().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spatchData%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getPatchData().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getPatchData().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

