/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.CreateFloorBodyProject;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * CreateUnitBody
 */
@JsonPropertyOrder({
  CreateUnitBody.JSON_PROPERTY_FLOOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-20T18:35:06.498112497Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class CreateUnitBody {
  public static final String JSON_PROPERTY_FLOOR = "floor";
  @javax.annotation.Nonnull
  private CreateFloorBodyProject floor;

  public CreateUnitBody() { 
  }

  public CreateUnitBody floor(@javax.annotation.Nonnull CreateFloorBodyProject floor) {
    this.floor = floor;
    return this;
  }

  /**
   * Get floor
   * @return floor
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLOOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CreateFloorBodyProject getFloor() {
    return floor;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFloor(@javax.annotation.Nonnull CreateFloorBodyProject floor) {
    this.floor = floor;
  }


  /**
   * Return true if this CreateUnitBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUnitBody createUnitBody = (CreateUnitBody) o;
    return Objects.equals(this.floor, createUnitBody.floor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(floor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUnitBody {\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `floor` to the URL query string
    if (getFloor() != null) {
      joiner.add(getFloor().toUrlQueryString(prefix + "floor" + suffix));
    }

    return joiner.toString();
  }
}

