/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.ErrorResponsePausedAnyOf;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.planpoint.ApiClient;
import io.planpoint.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-20T18:35:06.498112497Z[Etc/UTC]", comments = "Generator version: 7.21.0")
@JsonDeserialize(using=ErrorResponsePaused.ErrorResponsePausedDeserializer.class)
@JsonSerialize(using = ErrorResponsePaused.ErrorResponsePausedSerializer.class)
public class ErrorResponsePaused extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ErrorResponsePaused.class.getName());

    public static class ErrorResponsePausedSerializer extends StdSerializer<ErrorResponsePaused> {
        public ErrorResponsePausedSerializer(Class<ErrorResponsePaused> t) {
            super(t);
        }

        public ErrorResponsePausedSerializer() {
            this(null);
        }

        @Override
        public void serialize(ErrorResponsePaused value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ErrorResponsePausedDeserializer extends StdDeserializer<ErrorResponsePaused> {
        public ErrorResponsePausedDeserializer() {
            this(ErrorResponsePaused.class);
        }

        public ErrorResponsePausedDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ErrorResponsePaused deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);

            Object deserialized = null;
            // deserialize Boolean
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(Boolean.class);
                ErrorResponsePaused ret = new ErrorResponsePaused();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ErrorResponsePaused'", e);
            }

            // deserialize ErrorResponsePausedAnyOf
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(ErrorResponsePausedAnyOf.class);
                ErrorResponsePaused ret = new ErrorResponsePaused();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'ErrorResponsePaused'", e);
            }

            throw new IOException("Failed deserialization for ErrorResponsePaused: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ErrorResponsePaused getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "ErrorResponsePaused cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public ErrorResponsePaused() {
        super("anyOf", Boolean.FALSE);
    }

    public ErrorResponsePaused(Boolean o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ErrorResponsePaused(ErrorResponsePausedAnyOf o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Boolean", Boolean.class);
        schemas.put("ErrorResponsePausedAnyOf", ErrorResponsePausedAnyOf.class);
        JSON.registerDescendants(ErrorResponsePaused.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ErrorResponsePaused.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * Boolean, ErrorResponsePausedAnyOf
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Boolean.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ErrorResponsePausedAnyOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Boolean, ErrorResponsePausedAnyOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * Boolean, ErrorResponsePausedAnyOf
     *
     * @return The actual instance (Boolean, ErrorResponsePausedAnyOf)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Boolean`. If the actual instance is not `Boolean`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Boolean`
     * @throws ClassCastException if the instance is not `Boolean`
     */
    public Boolean getBoolean() throws ClassCastException {
        return (Boolean)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ErrorResponsePausedAnyOf`. If the actual instance is not `ErrorResponsePausedAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ErrorResponsePausedAnyOf`
     * @throws ClassCastException if the instance is not `ErrorResponsePausedAnyOf`
     */
    public ErrorResponsePausedAnyOf getErrorResponsePausedAnyOf() throws ClassCastException {
        return (ErrorResponsePausedAnyOf)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}

