/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * FloorFull
 */
@JsonPropertyOrder({
  FloorFull.JSON_PROPERTY_ID,
  FloorFull.JSON_PROPERTY_NAME,
  FloorFull.JSON_PROPERTY_PROJECT,
  FloorFull.JSON_PROPERTY_LEVEL,
  FloorFull.JSON_PROPERTY_POSITION,
  FloorFull.JSON_PROPERTY_PATH,
  FloorFull.JSON_PROPERTY_ALTERNATIVE_PATHS,
  FloorFull.JSON_PROPERTY_IMAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T18:57:29.273682275Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class FloorFull {
  public static final String JSON_PROPERTY_ID = "_id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PROJECT = "project";
  @javax.annotation.Nonnull
  private String project;

  public static final String JSON_PROPERTY_LEVEL = "level";
  @javax.annotation.Nullable
  private BigDecimal level;

  public static final String JSON_PROPERTY_POSITION = "position";
  @javax.annotation.Nullable
  private BigDecimal position;

  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_ALTERNATIVE_PATHS = "alternativePaths";
  @javax.annotation.Nullable
  private List<String> alternativePaths = new ArrayList<>();

  public static final String JSON_PROPERTY_IMAGE = "image";
  @javax.annotation.Nullable
  private URI image;

  public FloorFull() { 
  }

  public FloorFull id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public FloorFull name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public FloorFull project(@javax.annotation.Nonnull String project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProject() {
    return project;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProject(@javax.annotation.Nonnull String project) {
    this.project = project;
  }


  public FloorFull level(@javax.annotation.Nullable BigDecimal level) {
    this.level = level;
    return this;
  }

  /**
   * Get level
   * @return level
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getLevel() {
    return level;
  }


  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(@javax.annotation.Nullable BigDecimal level) {
    this.level = level;
  }


  public FloorFull position(@javax.annotation.Nullable BigDecimal position) {
    this.position = position;
    return this;
  }

  /**
   * Get position
   * @return position
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPosition() {
    return position;
  }


  @JsonProperty(value = JSON_PROPERTY_POSITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosition(@javax.annotation.Nullable BigDecimal position) {
    this.position = position;
  }


  public FloorFull path(@javax.annotation.Nullable String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@javax.annotation.Nullable String path) {
    this.path = path;
  }


  public FloorFull alternativePaths(@javax.annotation.Nullable List<String> alternativePaths) {
    this.alternativePaths = alternativePaths;
    return this;
  }

  public FloorFull addAlternativePathsItem(String alternativePathsItem) {
    if (this.alternativePaths == null) {
      this.alternativePaths = new ArrayList<>();
    }
    this.alternativePaths.add(alternativePathsItem);
    return this;
  }

  /**
   * Get alternativePaths
   * @return alternativePaths
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALTERNATIVE_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAlternativePaths() {
    return alternativePaths;
  }


  @JsonProperty(value = JSON_PROPERTY_ALTERNATIVE_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlternativePaths(@javax.annotation.Nullable List<String> alternativePaths) {
    this.alternativePaths = alternativePaths;
  }


  public FloorFull image(@javax.annotation.Nullable URI image) {
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getImage() {
    return image;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(@javax.annotation.Nullable URI image) {
    this.image = image;
  }


  /**
   * Return true if this FloorFull object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FloorFull floorFull = (FloorFull) o;
    return Objects.equals(this.id, floorFull.id) &&
        Objects.equals(this.name, floorFull.name) &&
        Objects.equals(this.project, floorFull.project) &&
        Objects.equals(this.level, floorFull.level) &&
        Objects.equals(this.position, floorFull.position) &&
        Objects.equals(this.path, floorFull.path) &&
        Objects.equals(this.alternativePaths, floorFull.alternativePaths) &&
        Objects.equals(this.image, floorFull.image);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, project, level, position, path, alternativePaths, image);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FloorFull {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    alternativePaths: ").append(toIndentedString(alternativePaths)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `_id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%s_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `project` to the URL query string
    if (getProject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProject()))));
    }

    // add `level` to the URL query string
    if (getLevel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slevel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLevel()))));
    }

    // add `position` to the URL query string
    if (getPosition() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sposition%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPosition()))));
    }

    // add `path` to the URL query string
    if (getPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPath()))));
    }

    // add `alternativePaths` to the URL query string
    if (getAlternativePaths() != null) {
      for (int i = 0; i < getAlternativePaths().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%salternativePaths%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAlternativePaths().get(i)))));
      }
    }

    // add `image` to the URL query string
    if (getImage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%simage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getImage()))));
    }

    return joiner.toString();
  }
}

