/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.Group;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * GroupsListResponse
 */
@JsonPropertyOrder({
  GroupsListResponse.JSON_PROPERTY_RECORDS,
  GroupsListResponse.JSON_PROPERTY_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T19:26:38.222016651Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class GroupsListResponse {
  public static final String JSON_PROPERTY_RECORDS = "records";
  @javax.annotation.Nonnull
  private List<Group> records = new ArrayList<>();

  public static final String JSON_PROPERTY_COUNT = "count";
  @javax.annotation.Nonnull
  private BigDecimal count;

  public GroupsListResponse() { 
  }

  public GroupsListResponse records(@javax.annotation.Nonnull List<Group> records) {
    this.records = records;
    return this;
  }

  public GroupsListResponse addRecordsItem(Group recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<>();
    }
    this.records.add(recordsItem);
    return this;
  }

  /**
   * Get records
   * @return records
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECORDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Group> getRecords() {
    return records;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecords(@javax.annotation.Nonnull List<Group> records) {
    this.records = records;
  }


  public GroupsListResponse count(@javax.annotation.Nonnull BigDecimal count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@javax.annotation.Nonnull BigDecimal count) {
    this.count = count;
  }


  /**
   * Return true if this GroupsListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupsListResponse groupsListResponse = (GroupsListResponse) o;
    return Objects.equals(this.records, groupsListResponse.records) &&
        Objects.equals(this.count, groupsListResponse.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(records, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupsListResponse {\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `records` to the URL query string
    if (getRecords() != null) {
      for (int i = 0; i < getRecords().size(); i++) {
        if (getRecords().get(i) != null) {
          joiner.add(getRecords().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%srecords%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `count` to the URL query string
    if (getCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCount()))));
    }

    return joiner.toString();
  }
}

