/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.GroupProjectsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * Group
 */
@JsonPropertyOrder({
  Group.JSON_PROPERTY_ID,
  Group.JSON_PROPERTY_NAME,
  Group.JSON_PROPERTY_NAMESPACE,
  Group.JSON_PROPERTY_HOST_NAME,
  Group.JSON_PROPERTY_TYPE,
  Group.JSON_PROPERTY_PROPERTY_TYPE,
  Group.JSON_PROPERTY_USER,
  Group.JSON_PROPERTY_PROJECTS,
  Group.JSON_PROPERTY_IS_OWNER,
  Group.JSON_PROPERTY_IS_ADMIN,
  Group.JSON_PROPERTY_IS_EDITOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-20T18:35:06.498112497Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class Group {
  public static final String JSON_PROPERTY_ID = "_id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @javax.annotation.Nullable
  private String namespace;

  public static final String JSON_PROPERTY_HOST_NAME = "hostName";
  @javax.annotation.Nullable
  private String hostName;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_PROPERTY_TYPE = "propertyType";
  @javax.annotation.Nullable
  private String propertyType;

  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nonnull
  private String user;

  public static final String JSON_PROPERTY_PROJECTS = "projects";
  @javax.annotation.Nullable
  private List<GroupProjectsInner> projects = new ArrayList<>();

  public static final String JSON_PROPERTY_IS_OWNER = "isOwner";
  @javax.annotation.Nullable
  private Boolean isOwner;

  public static final String JSON_PROPERTY_IS_ADMIN = "isAdmin";
  @javax.annotation.Nullable
  private Boolean isAdmin;

  public static final String JSON_PROPERTY_IS_EDITOR = "isEditor";
  @javax.annotation.Nullable
  private Boolean isEditor;

  public Group() { 
  }

  public Group id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Group name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Group namespace(@javax.annotation.Nullable String namespace) {
    this.namespace = namespace;
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespace(@javax.annotation.Nullable String namespace) {
    this.namespace = namespace;
  }


  public Group hostName(@javax.annotation.Nullable String hostName) {
    this.hostName = hostName;
    return this;
  }

  /**
   * Get hostName
   * @return hostName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHostName() {
    return hostName;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostName(@javax.annotation.Nullable String hostName) {
    this.hostName = hostName;
  }


  public Group type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public Group propertyType(@javax.annotation.Nullable String propertyType) {
    this.propertyType = propertyType;
    return this;
  }

  /**
   * Get propertyType
   * @return propertyType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPropertyType() {
    return propertyType;
  }


  @JsonProperty(value = JSON_PROPERTY_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyType(@javax.annotation.Nullable String propertyType) {
    this.propertyType = propertyType;
  }


  public Group user(@javax.annotation.Nonnull String user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUser() {
    return user;
  }


  @JsonProperty(value = JSON_PROPERTY_USER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUser(@javax.annotation.Nonnull String user) {
    this.user = user;
  }


  public Group projects(@javax.annotation.Nullable List<GroupProjectsInner> projects) {
    this.projects = projects;
    return this;
  }

  public Group addProjectsItem(GroupProjectsInner projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<>();
    }
    this.projects.add(projectsItem);
    return this;
  }

  /**
   * Get projects
   * @return projects
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GroupProjectsInner> getProjects() {
    return projects;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjects(@javax.annotation.Nullable List<GroupProjectsInner> projects) {
    this.projects = projects;
  }


  public Group isOwner(@javax.annotation.Nullable Boolean isOwner) {
    this.isOwner = isOwner;
    return this;
  }

  /**
   * Get isOwner
   * @return isOwner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsOwner() {
    return isOwner;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsOwner(@javax.annotation.Nullable Boolean isOwner) {
    this.isOwner = isOwner;
  }


  public Group isAdmin(@javax.annotation.Nullable Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

  /**
   * Get isAdmin
   * @return isAdmin
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_ADMIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsAdmin() {
    return isAdmin;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ADMIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAdmin(@javax.annotation.Nullable Boolean isAdmin) {
    this.isAdmin = isAdmin;
  }


  public Group isEditor(@javax.annotation.Nullable Boolean isEditor) {
    this.isEditor = isEditor;
    return this;
  }

  /**
   * Get isEditor
   * @return isEditor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_EDITOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsEditor() {
    return isEditor;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_EDITOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEditor(@javax.annotation.Nullable Boolean isEditor) {
    this.isEditor = isEditor;
  }


  /**
   * Return true if this Group object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Group group = (Group) o;
    return Objects.equals(this.id, group.id) &&
        Objects.equals(this.name, group.name) &&
        Objects.equals(this.namespace, group.namespace) &&
        Objects.equals(this.hostName, group.hostName) &&
        Objects.equals(this.type, group.type) &&
        Objects.equals(this.propertyType, group.propertyType) &&
        Objects.equals(this.user, group.user) &&
        Objects.equals(this.projects, group.projects) &&
        Objects.equals(this.isOwner, group.isOwner) &&
        Objects.equals(this.isAdmin, group.isAdmin) &&
        Objects.equals(this.isEditor, group.isEditor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, namespace, hostName, type, propertyType, user, projects, isOwner, isAdmin, isEditor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Group {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    propertyType: ").append(toIndentedString(propertyType)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    isOwner: ").append(toIndentedString(isOwner)).append("\n");
    sb.append("    isAdmin: ").append(toIndentedString(isAdmin)).append("\n");
    sb.append("    isEditor: ").append(toIndentedString(isEditor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `_id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%s_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `namespace` to the URL query string
    if (getNamespace() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snamespace%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNamespace()))));
    }

    // add `hostName` to the URL query string
    if (getHostName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shostName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHostName()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `propertyType` to the URL query string
    if (getPropertyType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spropertyType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPropertyType()))));
    }

    // add `user` to the URL query string
    if (getUser() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suser%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUser()))));
    }

    // add `projects` to the URL query string
    if (getProjects() != null) {
      for (int i = 0; i < getProjects().size(); i++) {
        if (getProjects().get(i) != null) {
          joiner.add(getProjects().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sprojects%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `isOwner` to the URL query string
    if (getIsOwner() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisOwner%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsOwner()))));
    }

    // add `isAdmin` to the URL query string
    if (getIsAdmin() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisAdmin%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsAdmin()))));
    }

    // add `isEditor` to the URL query string
    if (getIsEditor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisEditor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsEditor()))));
    }

    return joiner.toString();
  }
}

