/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.GroupProject;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.planpoint.ApiClient;
import io.planpoint.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T19:26:38.222016651Z[Etc/UTC]", comments = "Generator version: 7.21.0")
@JsonDeserialize(using=GroupProjectsInner.GroupProjectsInnerDeserializer.class)
@JsonSerialize(using = GroupProjectsInner.GroupProjectsInnerSerializer.class)
public class GroupProjectsInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GroupProjectsInner.class.getName());

    public static class GroupProjectsInnerSerializer extends StdSerializer<GroupProjectsInner> {
        public GroupProjectsInnerSerializer(Class<GroupProjectsInner> t) {
            super(t);
        }

        public GroupProjectsInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(GroupProjectsInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class GroupProjectsInnerDeserializer extends StdDeserializer<GroupProjectsInner> {
        public GroupProjectsInnerDeserializer() {
            this(GroupProjectsInner.class);
        }

        public GroupProjectsInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public GroupProjectsInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);

            Object deserialized = null;
            // deserialize GroupProject
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(GroupProject.class);
                GroupProjectsInner ret = new GroupProjectsInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'GroupProjectsInner'", e);
            }

            // deserialize String
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(String.class);
                GroupProjectsInner ret = new GroupProjectsInner();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'GroupProjectsInner'", e);
            }

            throw new IOException("Failed deserialization for GroupProjectsInner: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public GroupProjectsInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "GroupProjectsInner cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public GroupProjectsInner() {
        super("anyOf", Boolean.FALSE);
    }

    public GroupProjectsInner(GroupProject o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GroupProjectsInner(String o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GroupProject", GroupProject.class);
        schemas.put("String", String.class);
        JSON.registerDescendants(GroupProjectsInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GroupProjectsInner.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * GroupProject, String
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(GroupProject.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(String.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GroupProject, String");
    }

    /**
     * Get the actual instance, which can be the following:
     * GroupProject, String
     *
     * @return The actual instance (GroupProject, String)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GroupProject`. If the actual instance is not `GroupProject`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GroupProject`
     * @throws ClassCastException if the instance is not `GroupProject`
     */
    public GroupProject getGroupProject() throws ClassCastException {
        return (GroupProject)super.getActualInstance();
    }

    /**
     * Get the actual instance of `String`. If the actual instance is not `String`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `String`
     * @throws ClassCastException if the instance is not `String`
     */
    public String getString() throws ClassCastException {
        return (String)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return null;
  }

}

