/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.Collection;
import io.planpoint.model.CommercialSpace;
import io.planpoint.model.Floor;
import io.planpoint.model.ProjectCustomButtonTxt;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * Project
 */
@JsonPropertyOrder({
  Project.JSON_PROPERTY_ID,
  Project.JSON_PROPERTY_NAME,
  Project.JSON_PROPERTY_NAMESPACE,
  Project.JSON_PROPERTY_HOST_NAME,
  Project.JSON_PROPERTY_FLOORS,
  Project.JSON_PROPERTY_COMMERCIAL_SPACES,
  Project.JSON_PROPERTY_COLLECTIONS,
  Project.JSON_PROPERTY_PROJECT_LANG,
  Project.JSON_PROPERTY_STYLE_NAVIGATION,
  Project.JSON_PROPERTY_SHOW_PRICES,
  Project.JSON_PROPERTY_SHOW_AVAILABILITY,
  Project.JSON_PROPERTY_SHOW_BATHROOMS,
  Project.JSON_PROPERTY_SHOW_PARKING,
  Project.JSON_PROPERTY_SHOW_ORIENTATION,
  Project.JSON_PROPERTY_HIDE_SOLD,
  Project.JSON_PROPERTY_INITIAL_VIEW,
  Project.JSON_PROPERTY_LOGO,
  Project.JSON_PROPERTY_COVER_IMAGE,
  Project.JSON_PROPERTY_COLOR_BASE,
  Project.JSON_PROPERTY_COLOR_ACCENT,
  Project.JSON_PROPERTY_COLOR_BUTTON,
  Project.JSON_PROPERTY_COLOR_AVAILABLE,
  Project.JSON_PROPERTY_COLOR_SOLD,
  Project.JSON_PROPERTY_COLOR_RESERVED,
  Project.JSON_PROPERTY_CUSTOM_BUTTON_TXT,
  Project.JSON_PROPERTY_INTERNAL_U_R_LS,
  Project.JSON_PROPERTY_WEBSITE_U_R_L,
  Project.JSON_PROPERTY_CUSTOM_DOMAIN,
  Project.JSON_PROPERTY_SHARE_PAGE_ENABLED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-19T00:24:16.587565120Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class Project {
  public static final String JSON_PROPERTY_ID = "_id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @javax.annotation.Nonnull
  private String namespace;

  public static final String JSON_PROPERTY_HOST_NAME = "hostName";
  @javax.annotation.Nonnull
  private String hostName;

  public static final String JSON_PROPERTY_FLOORS = "floors";
  @javax.annotation.Nullable
  private List<Floor> floors = new ArrayList<>();

  public static final String JSON_PROPERTY_COMMERCIAL_SPACES = "commercialSpaces";
  @javax.annotation.Nullable
  private List<CommercialSpace> commercialSpaces = new ArrayList<>();

  public static final String JSON_PROPERTY_COLLECTIONS = "collections";
  @javax.annotation.Nullable
  private List<Collection> collections = new ArrayList<>();

  public static final String JSON_PROPERTY_PROJECT_LANG = "projectLang";
  @javax.annotation.Nullable
  private String projectLang;

  public static final String JSON_PROPERTY_STYLE_NAVIGATION = "styleNavigation";
  @javax.annotation.Nullable
  private String styleNavigation;

  public static final String JSON_PROPERTY_SHOW_PRICES = "showPrices";
  @javax.annotation.Nullable
  private Boolean showPrices;

  public static final String JSON_PROPERTY_SHOW_AVAILABILITY = "showAvailability";
  @javax.annotation.Nullable
  private Boolean showAvailability;

  public static final String JSON_PROPERTY_SHOW_BATHROOMS = "showBathrooms";
  @javax.annotation.Nullable
  private Boolean showBathrooms;

  public static final String JSON_PROPERTY_SHOW_PARKING = "showParking";
  @javax.annotation.Nullable
  private Boolean showParking;

  public static final String JSON_PROPERTY_SHOW_ORIENTATION = "showOrientation";
  @javax.annotation.Nullable
  private Boolean showOrientation;

  public static final String JSON_PROPERTY_HIDE_SOLD = "hideSold";
  @javax.annotation.Nullable
  private Boolean hideSold;

  public static final String JSON_PROPERTY_INITIAL_VIEW = "initialView";
  @javax.annotation.Nullable
  private String initialView;

  public static final String JSON_PROPERTY_LOGO = "logo";
  @javax.annotation.Nullable
  private URI logo;

  public static final String JSON_PROPERTY_COVER_IMAGE = "coverImage";
  @javax.annotation.Nullable
  private URI coverImage;

  public static final String JSON_PROPERTY_COLOR_BASE = "colorBase";
  @javax.annotation.Nullable
  private String colorBase;

  public static final String JSON_PROPERTY_COLOR_ACCENT = "colorAccent";
  @javax.annotation.Nullable
  private String colorAccent;

  public static final String JSON_PROPERTY_COLOR_BUTTON = "colorButton";
  @javax.annotation.Nullable
  private String colorButton;

  public static final String JSON_PROPERTY_COLOR_AVAILABLE = "colorAvailable";
  @javax.annotation.Nullable
  private String colorAvailable;

  public static final String JSON_PROPERTY_COLOR_SOLD = "colorSold";
  @javax.annotation.Nullable
  private String colorSold;

  public static final String JSON_PROPERTY_COLOR_RESERVED = "colorReserved";
  @javax.annotation.Nullable
  private String colorReserved;

  public static final String JSON_PROPERTY_CUSTOM_BUTTON_TXT = "customButtonTxt";
  @javax.annotation.Nullable
  private ProjectCustomButtonTxt customButtonTxt;

  public static final String JSON_PROPERTY_INTERNAL_U_R_LS = "internalURLs";
  @javax.annotation.Nullable
  private ProjectCustomButtonTxt internalURLs;

  public static final String JSON_PROPERTY_WEBSITE_U_R_L = "websiteURL";
  @javax.annotation.Nullable
  private URI websiteURL;

  public static final String JSON_PROPERTY_CUSTOM_DOMAIN = "customDomain";
  @javax.annotation.Nullable
  private String customDomain;

  public static final String JSON_PROPERTY_SHARE_PAGE_ENABLED = "sharePageEnabled";
  @javax.annotation.Nullable
  private Boolean sharePageEnabled;

  public Project() { 
  }

  public Project id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Project name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Project namespace(@javax.annotation.Nonnull String namespace) {
    this.namespace = namespace;
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNamespace(@javax.annotation.Nonnull String namespace) {
    this.namespace = namespace;
  }


  public Project hostName(@javax.annotation.Nonnull String hostName) {
    this.hostName = hostName;
    return this;
  }

  /**
   * Get hostName
   * @return hostName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHostName() {
    return hostName;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHostName(@javax.annotation.Nonnull String hostName) {
    this.hostName = hostName;
  }


  public Project floors(@javax.annotation.Nullable List<Floor> floors) {
    this.floors = floors;
    return this;
  }

  public Project addFloorsItem(Floor floorsItem) {
    if (this.floors == null) {
      this.floors = new ArrayList<>();
    }
    this.floors.add(floorsItem);
    return this;
  }

  /**
   * Get floors
   * @return floors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLOORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Floor> getFloors() {
    return floors;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFloors(@javax.annotation.Nullable List<Floor> floors) {
    this.floors = floors;
  }


  public Project commercialSpaces(@javax.annotation.Nullable List<CommercialSpace> commercialSpaces) {
    this.commercialSpaces = commercialSpaces;
    return this;
  }

  public Project addCommercialSpacesItem(CommercialSpace commercialSpacesItem) {
    if (this.commercialSpaces == null) {
      this.commercialSpaces = new ArrayList<>();
    }
    this.commercialSpaces.add(commercialSpacesItem);
    return this;
  }

  /**
   * Get commercialSpaces
   * @return commercialSpaces
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMERCIAL_SPACES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<CommercialSpace> getCommercialSpaces() {
    return commercialSpaces;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMERCIAL_SPACES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommercialSpaces(@javax.annotation.Nullable List<CommercialSpace> commercialSpaces) {
    this.commercialSpaces = commercialSpaces;
  }


  public Project collections(@javax.annotation.Nullable List<Collection> collections) {
    this.collections = collections;
    return this;
  }

  public Project addCollectionsItem(Collection collectionsItem) {
    if (this.collections == null) {
      this.collections = new ArrayList<>();
    }
    this.collections.add(collectionsItem);
    return this;
  }

  /**
   * Get collections
   * @return collections
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLLECTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Collection> getCollections() {
    return collections;
  }


  @JsonProperty(value = JSON_PROPERTY_COLLECTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCollections(@javax.annotation.Nullable List<Collection> collections) {
    this.collections = collections;
  }


  public Project projectLang(@javax.annotation.Nullable String projectLang) {
    this.projectLang = projectLang;
    return this;
  }

  /**
   * Get projectLang
   * @return projectLang
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_LANG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectLang() {
    return projectLang;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_LANG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectLang(@javax.annotation.Nullable String projectLang) {
    this.projectLang = projectLang;
  }


  public Project styleNavigation(@javax.annotation.Nullable String styleNavigation) {
    this.styleNavigation = styleNavigation;
    return this;
  }

  /**
   * Get styleNavigation
   * @return styleNavigation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STYLE_NAVIGATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStyleNavigation() {
    return styleNavigation;
  }


  @JsonProperty(value = JSON_PROPERTY_STYLE_NAVIGATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyleNavigation(@javax.annotation.Nullable String styleNavigation) {
    this.styleNavigation = styleNavigation;
  }


  public Project showPrices(@javax.annotation.Nullable Boolean showPrices) {
    this.showPrices = showPrices;
    return this;
  }

  /**
   * Get showPrices
   * @return showPrices
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_PRICES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowPrices() {
    return showPrices;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_PRICES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowPrices(@javax.annotation.Nullable Boolean showPrices) {
    this.showPrices = showPrices;
  }


  public Project showAvailability(@javax.annotation.Nullable Boolean showAvailability) {
    this.showAvailability = showAvailability;
    return this;
  }

  /**
   * Get showAvailability
   * @return showAvailability
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_AVAILABILITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowAvailability() {
    return showAvailability;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_AVAILABILITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowAvailability(@javax.annotation.Nullable Boolean showAvailability) {
    this.showAvailability = showAvailability;
  }


  public Project showBathrooms(@javax.annotation.Nullable Boolean showBathrooms) {
    this.showBathrooms = showBathrooms;
    return this;
  }

  /**
   * Get showBathrooms
   * @return showBathrooms
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_BATHROOMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowBathrooms() {
    return showBathrooms;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_BATHROOMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowBathrooms(@javax.annotation.Nullable Boolean showBathrooms) {
    this.showBathrooms = showBathrooms;
  }


  public Project showParking(@javax.annotation.Nullable Boolean showParking) {
    this.showParking = showParking;
    return this;
  }

  /**
   * Get showParking
   * @return showParking
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_PARKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowParking() {
    return showParking;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_PARKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowParking(@javax.annotation.Nullable Boolean showParking) {
    this.showParking = showParking;
  }


  public Project showOrientation(@javax.annotation.Nullable Boolean showOrientation) {
    this.showOrientation = showOrientation;
    return this;
  }

  /**
   * Get showOrientation
   * @return showOrientation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOW_ORIENTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShowOrientation() {
    return showOrientation;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOW_ORIENTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowOrientation(@javax.annotation.Nullable Boolean showOrientation) {
    this.showOrientation = showOrientation;
  }


  public Project hideSold(@javax.annotation.Nullable Boolean hideSold) {
    this.hideSold = hideSold;
    return this;
  }

  /**
   * Get hideSold
   * @return hideSold
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIDE_SOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHideSold() {
    return hideSold;
  }


  @JsonProperty(value = JSON_PROPERTY_HIDE_SOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHideSold(@javax.annotation.Nullable Boolean hideSold) {
    this.hideSold = hideSold;
  }


  public Project initialView(@javax.annotation.Nullable String initialView) {
    this.initialView = initialView;
    return this;
  }

  /**
   * Get initialView
   * @return initialView
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INITIAL_VIEW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInitialView() {
    return initialView;
  }


  @JsonProperty(value = JSON_PROPERTY_INITIAL_VIEW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInitialView(@javax.annotation.Nullable String initialView) {
    this.initialView = initialView;
  }


  public Project logo(@javax.annotation.Nullable URI logo) {
    this.logo = logo;
    return this;
  }

  /**
   * Get logo
   * @return logo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getLogo() {
    return logo;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogo(@javax.annotation.Nullable URI logo) {
    this.logo = logo;
  }


  public Project coverImage(@javax.annotation.Nullable URI coverImage) {
    this.coverImage = coverImage;
    return this;
  }

  /**
   * Get coverImage
   * @return coverImage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COVER_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getCoverImage() {
    return coverImage;
  }


  @JsonProperty(value = JSON_PROPERTY_COVER_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoverImage(@javax.annotation.Nullable URI coverImage) {
    this.coverImage = coverImage;
  }


  public Project colorBase(@javax.annotation.Nullable String colorBase) {
    this.colorBase = colorBase;
    return this;
  }

  /**
   * Get colorBase
   * @return colorBase
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR_BASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColorBase() {
    return colorBase;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR_BASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColorBase(@javax.annotation.Nullable String colorBase) {
    this.colorBase = colorBase;
  }


  public Project colorAccent(@javax.annotation.Nullable String colorAccent) {
    this.colorAccent = colorAccent;
    return this;
  }

  /**
   * Get colorAccent
   * @return colorAccent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR_ACCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColorAccent() {
    return colorAccent;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR_ACCENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColorAccent(@javax.annotation.Nullable String colorAccent) {
    this.colorAccent = colorAccent;
  }


  public Project colorButton(@javax.annotation.Nullable String colorButton) {
    this.colorButton = colorButton;
    return this;
  }

  /**
   * Get colorButton
   * @return colorButton
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR_BUTTON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColorButton() {
    return colorButton;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR_BUTTON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColorButton(@javax.annotation.Nullable String colorButton) {
    this.colorButton = colorButton;
  }


  public Project colorAvailable(@javax.annotation.Nullable String colorAvailable) {
    this.colorAvailable = colorAvailable;
    return this;
  }

  /**
   * Get colorAvailable
   * @return colorAvailable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColorAvailable() {
    return colorAvailable;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColorAvailable(@javax.annotation.Nullable String colorAvailable) {
    this.colorAvailable = colorAvailable;
  }


  public Project colorSold(@javax.annotation.Nullable String colorSold) {
    this.colorSold = colorSold;
    return this;
  }

  /**
   * Get colorSold
   * @return colorSold
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR_SOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColorSold() {
    return colorSold;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR_SOLD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColorSold(@javax.annotation.Nullable String colorSold) {
    this.colorSold = colorSold;
  }


  public Project colorReserved(@javax.annotation.Nullable String colorReserved) {
    this.colorReserved = colorReserved;
    return this;
  }

  /**
   * Get colorReserved
   * @return colorReserved
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR_RESERVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getColorReserved() {
    return colorReserved;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR_RESERVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColorReserved(@javax.annotation.Nullable String colorReserved) {
    this.colorReserved = colorReserved;
  }


  public Project customButtonTxt(@javax.annotation.Nullable ProjectCustomButtonTxt customButtonTxt) {
    this.customButtonTxt = customButtonTxt;
    return this;
  }

  /**
   * Get customButtonTxt
   * @return customButtonTxt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_BUTTON_TXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProjectCustomButtonTxt getCustomButtonTxt() {
    return customButtonTxt;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_BUTTON_TXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomButtonTxt(@javax.annotation.Nullable ProjectCustomButtonTxt customButtonTxt) {
    this.customButtonTxt = customButtonTxt;
  }


  public Project internalURLs(@javax.annotation.Nullable ProjectCustomButtonTxt internalURLs) {
    this.internalURLs = internalURLs;
    return this;
  }

  /**
   * Get internalURLs
   * @return internalURLs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTERNAL_U_R_LS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProjectCustomButtonTxt getInternalURLs() {
    return internalURLs;
  }


  @JsonProperty(value = JSON_PROPERTY_INTERNAL_U_R_LS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternalURLs(@javax.annotation.Nullable ProjectCustomButtonTxt internalURLs) {
    this.internalURLs = internalURLs;
  }


  public Project websiteURL(@javax.annotation.Nullable URI websiteURL) {
    this.websiteURL = websiteURL;
    return this;
  }

  /**
   * Get websiteURL
   * @return websiteURL
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBSITE_U_R_L, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getWebsiteURL() {
    return websiteURL;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBSITE_U_R_L, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsiteURL(@javax.annotation.Nullable URI websiteURL) {
    this.websiteURL = websiteURL;
  }


  public Project customDomain(@javax.annotation.Nullable String customDomain) {
    this.customDomain = customDomain;
    return this;
  }

  /**
   * Get customDomain
   * @return customDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCustomDomain() {
    return customDomain;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomDomain(@javax.annotation.Nullable String customDomain) {
    this.customDomain = customDomain;
  }


  public Project sharePageEnabled(@javax.annotation.Nullable Boolean sharePageEnabled) {
    this.sharePageEnabled = sharePageEnabled;
    return this;
  }

  /**
   * Get sharePageEnabled
   * @return sharePageEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHARE_PAGE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSharePageEnabled() {
    return sharePageEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_SHARE_PAGE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSharePageEnabled(@javax.annotation.Nullable Boolean sharePageEnabled) {
    this.sharePageEnabled = sharePageEnabled;
  }


  /**
   * Return true if this Project object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Project project = (Project) o;
    return Objects.equals(this.id, project.id) &&
        Objects.equals(this.name, project.name) &&
        Objects.equals(this.namespace, project.namespace) &&
        Objects.equals(this.hostName, project.hostName) &&
        Objects.equals(this.floors, project.floors) &&
        Objects.equals(this.commercialSpaces, project.commercialSpaces) &&
        Objects.equals(this.collections, project.collections) &&
        Objects.equals(this.projectLang, project.projectLang) &&
        Objects.equals(this.styleNavigation, project.styleNavigation) &&
        Objects.equals(this.showPrices, project.showPrices) &&
        Objects.equals(this.showAvailability, project.showAvailability) &&
        Objects.equals(this.showBathrooms, project.showBathrooms) &&
        Objects.equals(this.showParking, project.showParking) &&
        Objects.equals(this.showOrientation, project.showOrientation) &&
        Objects.equals(this.hideSold, project.hideSold) &&
        Objects.equals(this.initialView, project.initialView) &&
        Objects.equals(this.logo, project.logo) &&
        Objects.equals(this.coverImage, project.coverImage) &&
        Objects.equals(this.colorBase, project.colorBase) &&
        Objects.equals(this.colorAccent, project.colorAccent) &&
        Objects.equals(this.colorButton, project.colorButton) &&
        Objects.equals(this.colorAvailable, project.colorAvailable) &&
        Objects.equals(this.colorSold, project.colorSold) &&
        Objects.equals(this.colorReserved, project.colorReserved) &&
        Objects.equals(this.customButtonTxt, project.customButtonTxt) &&
        Objects.equals(this.internalURLs, project.internalURLs) &&
        Objects.equals(this.websiteURL, project.websiteURL) &&
        Objects.equals(this.customDomain, project.customDomain) &&
        Objects.equals(this.sharePageEnabled, project.sharePageEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, namespace, hostName, floors, commercialSpaces, collections, projectLang, styleNavigation, showPrices, showAvailability, showBathrooms, showParking, showOrientation, hideSold, initialView, logo, coverImage, colorBase, colorAccent, colorButton, colorAvailable, colorSold, colorReserved, customButtonTxt, internalURLs, websiteURL, customDomain, sharePageEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Project {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    floors: ").append(toIndentedString(floors)).append("\n");
    sb.append("    commercialSpaces: ").append(toIndentedString(commercialSpaces)).append("\n");
    sb.append("    collections: ").append(toIndentedString(collections)).append("\n");
    sb.append("    projectLang: ").append(toIndentedString(projectLang)).append("\n");
    sb.append("    styleNavigation: ").append(toIndentedString(styleNavigation)).append("\n");
    sb.append("    showPrices: ").append(toIndentedString(showPrices)).append("\n");
    sb.append("    showAvailability: ").append(toIndentedString(showAvailability)).append("\n");
    sb.append("    showBathrooms: ").append(toIndentedString(showBathrooms)).append("\n");
    sb.append("    showParking: ").append(toIndentedString(showParking)).append("\n");
    sb.append("    showOrientation: ").append(toIndentedString(showOrientation)).append("\n");
    sb.append("    hideSold: ").append(toIndentedString(hideSold)).append("\n");
    sb.append("    initialView: ").append(toIndentedString(initialView)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    coverImage: ").append(toIndentedString(coverImage)).append("\n");
    sb.append("    colorBase: ").append(toIndentedString(colorBase)).append("\n");
    sb.append("    colorAccent: ").append(toIndentedString(colorAccent)).append("\n");
    sb.append("    colorButton: ").append(toIndentedString(colorButton)).append("\n");
    sb.append("    colorAvailable: ").append(toIndentedString(colorAvailable)).append("\n");
    sb.append("    colorSold: ").append(toIndentedString(colorSold)).append("\n");
    sb.append("    colorReserved: ").append(toIndentedString(colorReserved)).append("\n");
    sb.append("    customButtonTxt: ").append(toIndentedString(customButtonTxt)).append("\n");
    sb.append("    internalURLs: ").append(toIndentedString(internalURLs)).append("\n");
    sb.append("    websiteURL: ").append(toIndentedString(websiteURL)).append("\n");
    sb.append("    customDomain: ").append(toIndentedString(customDomain)).append("\n");
    sb.append("    sharePageEnabled: ").append(toIndentedString(sharePageEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `_id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%s_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `namespace` to the URL query string
    if (getNamespace() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snamespace%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNamespace()))));
    }

    // add `hostName` to the URL query string
    if (getHostName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shostName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHostName()))));
    }

    // add `floors` to the URL query string
    if (getFloors() != null) {
      for (int i = 0; i < getFloors().size(); i++) {
        if (getFloors().get(i) != null) {
          joiner.add(getFloors().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sfloors%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `commercialSpaces` to the URL query string
    if (getCommercialSpaces() != null) {
      for (int i = 0; i < getCommercialSpaces().size(); i++) {
        if (getCommercialSpaces().get(i) != null) {
          joiner.add(getCommercialSpaces().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scommercialSpaces%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `collections` to the URL query string
    if (getCollections() != null) {
      for (int i = 0; i < getCollections().size(); i++) {
        if (getCollections().get(i) != null) {
          joiner.add(getCollections().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scollections%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `projectLang` to the URL query string
    if (getProjectLang() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprojectLang%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectLang()))));
    }

    // add `styleNavigation` to the URL query string
    if (getStyleNavigation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstyleNavigation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStyleNavigation()))));
    }

    // add `showPrices` to the URL query string
    if (getShowPrices() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowPrices%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowPrices()))));
    }

    // add `showAvailability` to the URL query string
    if (getShowAvailability() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowAvailability%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowAvailability()))));
    }

    // add `showBathrooms` to the URL query string
    if (getShowBathrooms() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowBathrooms%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowBathrooms()))));
    }

    // add `showParking` to the URL query string
    if (getShowParking() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowParking%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowParking()))));
    }

    // add `showOrientation` to the URL query string
    if (getShowOrientation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sshowOrientation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShowOrientation()))));
    }

    // add `hideSold` to the URL query string
    if (getHideSold() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shideSold%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHideSold()))));
    }

    // add `initialView` to the URL query string
    if (getInitialView() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinitialView%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInitialView()))));
    }

    // add `logo` to the URL query string
    if (getLogo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slogo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLogo()))));
    }

    // add `coverImage` to the URL query string
    if (getCoverImage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scoverImage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCoverImage()))));
    }

    // add `colorBase` to the URL query string
    if (getColorBase() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolorBase%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColorBase()))));
    }

    // add `colorAccent` to the URL query string
    if (getColorAccent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolorAccent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColorAccent()))));
    }

    // add `colorButton` to the URL query string
    if (getColorButton() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolorButton%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColorButton()))));
    }

    // add `colorAvailable` to the URL query string
    if (getColorAvailable() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolorAvailable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColorAvailable()))));
    }

    // add `colorSold` to the URL query string
    if (getColorSold() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolorSold%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColorSold()))));
    }

    // add `colorReserved` to the URL query string
    if (getColorReserved() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scolorReserved%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColorReserved()))));
    }

    // add `customButtonTxt` to the URL query string
    if (getCustomButtonTxt() != null) {
      joiner.add(getCustomButtonTxt().toUrlQueryString(prefix + "customButtonTxt" + suffix));
    }

    // add `internalURLs` to the URL query string
    if (getInternalURLs() != null) {
      joiner.add(getInternalURLs().toUrlQueryString(prefix + "internalURLs" + suffix));
    }

    // add `websiteURL` to the URL query string
    if (getWebsiteURL() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebsiteURL%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebsiteURL()))));
    }

    // add `customDomain` to the URL query string
    if (getCustomDomain() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomDomain%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomDomain()))));
    }

    // add `sharePageEnabled` to the URL query string
    if (getSharePageEnabled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssharePageEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSharePageEnabled()))));
    }

    return joiner.toString();
  }
}

