/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.ErrorResponsePaused;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * ProjectSummary
 */
@JsonPropertyOrder({
  ProjectSummary.JSON_PROPERTY_ID,
  ProjectSummary.JSON_PROPERTY_NAME,
  ProjectSummary.JSON_PROPERTY_NAMESPACE,
  ProjectSummary.JSON_PROPERTY_HOST_NAME,
  ProjectSummary.JSON_PROPERTY_PROJECT_TYPE,
  ProjectSummary.JSON_PROPERTY_STATUS,
  ProjectSummary.JSON_PROPERTY_STATUS_OVERRIDE,
  ProjectSummary.JSON_PROPERTY_PAUSED,
  ProjectSummary.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T19:26:38.222016651Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class ProjectSummary {
  public static final String JSON_PROPERTY_ID = "_id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @javax.annotation.Nullable
  private String namespace;

  public static final String JSON_PROPERTY_HOST_NAME = "hostName";
  @javax.annotation.Nullable
  private String hostName;

  public static final String JSON_PROPERTY_PROJECT_TYPE = "projectType";
  @javax.annotation.Nullable
  private String projectType;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_STATUS_OVERRIDE = "statusOverride";
  @javax.annotation.Nullable
  private String statusOverride;

  public static final String JSON_PROPERTY_PAUSED = "paused";
  @javax.annotation.Nullable
  private ErrorResponsePaused paused;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private String createdAt;

  public ProjectSummary() { 
  }

  public ProjectSummary id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public ProjectSummary name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public ProjectSummary namespace(@javax.annotation.Nullable String namespace) {
    this.namespace = namespace;
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(value = JSON_PROPERTY_NAMESPACE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespace(@javax.annotation.Nullable String namespace) {
    this.namespace = namespace;
  }


  public ProjectSummary hostName(@javax.annotation.Nullable String hostName) {
    this.hostName = hostName;
    return this;
  }

  /**
   * Get hostName
   * @return hostName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHostName() {
    return hostName;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostName(@javax.annotation.Nullable String hostName) {
    this.hostName = hostName;
  }


  public ProjectSummary projectType(@javax.annotation.Nullable String projectType) {
    this.projectType = projectType;
    return this;
  }

  /**
   * Get projectType
   * @return projectType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProjectType() {
    return projectType;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectType(@javax.annotation.Nullable String projectType) {
    this.projectType = projectType;
  }


  public ProjectSummary status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ProjectSummary statusOverride(@javax.annotation.Nullable String statusOverride) {
    this.statusOverride = statusOverride;
    return this;
  }

  /**
   * Get statusOverride
   * @return statusOverride
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_OVERRIDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatusOverride() {
    return statusOverride;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_OVERRIDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusOverride(@javax.annotation.Nullable String statusOverride) {
    this.statusOverride = statusOverride;
  }


  public ProjectSummary paused(@javax.annotation.Nullable ErrorResponsePaused paused) {
    this.paused = paused;
    return this;
  }

  /**
   * Get paused
   * @return paused
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAUSED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ErrorResponsePaused getPaused() {
    return paused;
  }


  @JsonProperty(value = JSON_PROPERTY_PAUSED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaused(@javax.annotation.Nullable ErrorResponsePaused paused) {
    this.paused = paused;
  }


  public ProjectSummary createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this ProjectSummary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectSummary projectSummary = (ProjectSummary) o;
    return Objects.equals(this.id, projectSummary.id) &&
        Objects.equals(this.name, projectSummary.name) &&
        Objects.equals(this.namespace, projectSummary.namespace) &&
        Objects.equals(this.hostName, projectSummary.hostName) &&
        Objects.equals(this.projectType, projectSummary.projectType) &&
        Objects.equals(this.status, projectSummary.status) &&
        Objects.equals(this.statusOverride, projectSummary.statusOverride) &&
        Objects.equals(this.paused, projectSummary.paused) &&
        Objects.equals(this.createdAt, projectSummary.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, namespace, hostName, projectType, status, statusOverride, paused, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectSummary {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    projectType: ").append(toIndentedString(projectType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusOverride: ").append(toIndentedString(statusOverride)).append("\n");
    sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `_id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%s_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `namespace` to the URL query string
    if (getNamespace() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snamespace%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNamespace()))));
    }

    // add `hostName` to the URL query string
    if (getHostName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shostName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHostName()))));
    }

    // add `projectType` to the URL query string
    if (getProjectType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprojectType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `statusOverride` to the URL query string
    if (getStatusOverride() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatusOverride%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusOverride()))));
    }

    // add `paused` to the URL query string
    if (getPaused() != null) {
      joiner.add(getPaused().toUrlQueryString(prefix + "paused" + suffix));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

