/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * Translated string per language code
 */
@JsonPropertyOrder({
  ProjectCustomButtonTxt.JSON_PROPERTY_EN,
  ProjectCustomButtonTxt.JSON_PROPERTY_FR,
  ProjectCustomButtonTxt.JSON_PROPERTY_DE,
  ProjectCustomButtonTxt.JSON_PROPERTY_ES,
  ProjectCustomButtonTxt.JSON_PROPERTY_ZH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-19T00:24:16.587565120Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class ProjectCustomButtonTxt {
  public static final String JSON_PROPERTY_EN = "en";
  @javax.annotation.Nullable
  private String en;

  public static final String JSON_PROPERTY_FR = "fr";
  @javax.annotation.Nullable
  private String fr;

  public static final String JSON_PROPERTY_DE = "de";
  @javax.annotation.Nullable
  private String de;

  public static final String JSON_PROPERTY_ES = "es";
  @javax.annotation.Nullable
  private String es;

  public static final String JSON_PROPERTY_ZH = "zh";
  @javax.annotation.Nullable
  private String zh;

  public ProjectCustomButtonTxt() { 
  }

  public ProjectCustomButtonTxt en(@javax.annotation.Nullable String en) {
    this.en = en;
    return this;
  }

  /**
   * Get en
   * @return en
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEn() {
    return en;
  }


  @JsonProperty(value = JSON_PROPERTY_EN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEn(@javax.annotation.Nullable String en) {
    this.en = en;
  }


  public ProjectCustomButtonTxt fr(@javax.annotation.Nullable String fr) {
    this.fr = fr;
    return this;
  }

  /**
   * Get fr
   * @return fr
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFr() {
    return fr;
  }


  @JsonProperty(value = JSON_PROPERTY_FR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFr(@javax.annotation.Nullable String fr) {
    this.fr = fr;
  }


  public ProjectCustomButtonTxt de(@javax.annotation.Nullable String de) {
    this.de = de;
    return this;
  }

  /**
   * Get de
   * @return de
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDe() {
    return de;
  }


  @JsonProperty(value = JSON_PROPERTY_DE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDe(@javax.annotation.Nullable String de) {
    this.de = de;
  }


  public ProjectCustomButtonTxt es(@javax.annotation.Nullable String es) {
    this.es = es;
    return this;
  }

  /**
   * Get es
   * @return es
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEs() {
    return es;
  }


  @JsonProperty(value = JSON_PROPERTY_ES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEs(@javax.annotation.Nullable String es) {
    this.es = es;
  }


  public ProjectCustomButtonTxt zh(@javax.annotation.Nullable String zh) {
    this.zh = zh;
    return this;
  }

  /**
   * Get zh
   * @return zh
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ZH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getZh() {
    return zh;
  }


  @JsonProperty(value = JSON_PROPERTY_ZH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZh(@javax.annotation.Nullable String zh) {
    this.zh = zh;
  }


  /**
   * Return true if this Project_customButtonTxt object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectCustomButtonTxt projectCustomButtonTxt = (ProjectCustomButtonTxt) o;
    return Objects.equals(this.en, projectCustomButtonTxt.en) &&
        Objects.equals(this.fr, projectCustomButtonTxt.fr) &&
        Objects.equals(this.de, projectCustomButtonTxt.de) &&
        Objects.equals(this.es, projectCustomButtonTxt.es) &&
        Objects.equals(this.zh, projectCustomButtonTxt.zh);
  }

  @Override
  public int hashCode() {
    return Objects.hash(en, fr, de, es, zh);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectCustomButtonTxt {\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    fr: ").append(toIndentedString(fr)).append("\n");
    sb.append("    de: ").append(toIndentedString(de)).append("\n");
    sb.append("    es: ").append(toIndentedString(es)).append("\n");
    sb.append("    zh: ").append(toIndentedString(zh)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `en` to the URL query string
    if (getEn() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEn()))));
    }

    // add `fr` to the URL query string
    if (getFr() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfr%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFr()))));
    }

    // add `de` to the URL query string
    if (getDe() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sde%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDe()))));
    }

    // add `es` to the URL query string
    if (getEs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ses%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEs()))));
    }

    // add `zh` to the URL query string
    if (getZh() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%szh%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getZh()))));
    }

    return joiner.toString();
  }
}

