/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.planpoint.ApiClient;
/**
 * UnitFull
 */
@JsonPropertyOrder({
  UnitFull.JSON_PROPERTY_ID,
  UnitFull.JSON_PROPERTY_FLOOR,
  UnitFull.JSON_PROPERTY_NAME,
  UnitFull.JSON_PROPERTY_UNIT_NUMBER,
  UnitFull.JSON_PROPERTY_STATUS,
  UnitFull.JSON_PROPERTY_PRICE,
  UnitFull.JSON_PROPERTY_BED,
  UnitFull.JSON_PROPERTY_BATH,
  UnitFull.JSON_PROPERTY_SQFT,
  UnitFull.JSON_PROPERTY_MODEL,
  UnitFull.JSON_PROPERTY_ORIENTATION,
  UnitFull.JSON_PROPERTY_PARKING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T18:57:29.273682275Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class UnitFull {
  public static final String JSON_PROPERTY_ID = "_id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_FLOOR = "floor";
  @javax.annotation.Nonnull
  private String floor;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_UNIT_NUMBER = "unitNumber";
  @javax.annotation.Nullable
  private String unitNumber;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    AVAILABLE(String.valueOf("Available")),
    
    ON_HOLD(String.valueOf("OnHold")),
    
    SOLD(String.valueOf("Sold")),
    
    LEASED(String.valueOf("Leased")),
    
    UNAVAILABLE(String.valueOf("Unavailable"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_PRICE = "price";
  @javax.annotation.Nullable
  private BigDecimal price;

  public static final String JSON_PROPERTY_BED = "bed";
  @javax.annotation.Nullable
  private BigDecimal bed;

  public static final String JSON_PROPERTY_BATH = "bath";
  @javax.annotation.Nullable
  private BigDecimal bath;

  public static final String JSON_PROPERTY_SQFT = "sqft";
  @javax.annotation.Nullable
  private BigDecimal sqft;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nullable
  private String model;

  public static final String JSON_PROPERTY_ORIENTATION = "orientation";
  @javax.annotation.Nullable
  private String orientation;

  public static final String JSON_PROPERTY_PARKING = "parking";
  @javax.annotation.Nullable
  private BigDecimal parking;

  public UnitFull() { 
  }

  public UnitFull id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public UnitFull floor(@javax.annotation.Nonnull String floor) {
    this.floor = floor;
    return this;
  }

  /**
   * Get floor
   * @return floor
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLOOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFloor() {
    return floor;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFloor(@javax.annotation.Nonnull String floor) {
    this.floor = floor;
  }


  public UnitFull name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public UnitFull unitNumber(@javax.annotation.Nullable String unitNumber) {
    this.unitNumber = unitNumber;
    return this;
  }

  /**
   * Get unitNumber
   * @return unitNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNIT_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUnitNumber() {
    return unitNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_UNIT_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnitNumber(@javax.annotation.Nullable String unitNumber) {
    this.unitNumber = unitNumber;
  }


  public UnitFull status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public UnitFull price(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(value = JSON_PROPERTY_PRICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
  }


  public UnitFull bed(@javax.annotation.Nullable BigDecimal bed) {
    this.bed = bed;
    return this;
  }

  /**
   * Get bed
   * @return bed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBed() {
    return bed;
  }


  @JsonProperty(value = JSON_PROPERTY_BED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBed(@javax.annotation.Nullable BigDecimal bed) {
    this.bed = bed;
  }


  public UnitFull bath(@javax.annotation.Nullable BigDecimal bath) {
    this.bath = bath;
    return this;
  }

  /**
   * Get bath
   * @return bath
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getBath() {
    return bath;
  }


  @JsonProperty(value = JSON_PROPERTY_BATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBath(@javax.annotation.Nullable BigDecimal bath) {
    this.bath = bath;
  }


  public UnitFull sqft(@javax.annotation.Nullable BigDecimal sqft) {
    this.sqft = sqft;
    return this;
  }

  /**
   * Get sqft
   * @return sqft
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SQFT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getSqft() {
    return sqft;
  }


  @JsonProperty(value = JSON_PROPERTY_SQFT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSqft(@javax.annotation.Nullable BigDecimal sqft) {
    this.sqft = sqft;
  }


  public UnitFull model(@javax.annotation.Nullable String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(@javax.annotation.Nullable String model) {
    this.model = model;
  }


  public UnitFull orientation(@javax.annotation.Nullable String orientation) {
    this.orientation = orientation;
    return this;
  }

  /**
   * Get orientation
   * @return orientation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIENTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrientation() {
    return orientation;
  }


  @JsonProperty(value = JSON_PROPERTY_ORIENTATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrientation(@javax.annotation.Nullable String orientation) {
    this.orientation = orientation;
  }


  public UnitFull parking(@javax.annotation.Nullable BigDecimal parking) {
    this.parking = parking;
    return this;
  }

  /**
   * Get parking
   * @return parking
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getParking() {
    return parking;
  }


  @JsonProperty(value = JSON_PROPERTY_PARKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParking(@javax.annotation.Nullable BigDecimal parking) {
    this.parking = parking;
  }


  /**
   * Return true if this UnitFull object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnitFull unitFull = (UnitFull) o;
    return Objects.equals(this.id, unitFull.id) &&
        Objects.equals(this.floor, unitFull.floor) &&
        Objects.equals(this.name, unitFull.name) &&
        Objects.equals(this.unitNumber, unitFull.unitNumber) &&
        Objects.equals(this.status, unitFull.status) &&
        Objects.equals(this.price, unitFull.price) &&
        Objects.equals(this.bed, unitFull.bed) &&
        Objects.equals(this.bath, unitFull.bath) &&
        Objects.equals(this.sqft, unitFull.sqft) &&
        Objects.equals(this.model, unitFull.model) &&
        Objects.equals(this.orientation, unitFull.orientation) &&
        Objects.equals(this.parking, unitFull.parking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, floor, name, unitNumber, status, price, bed, bath, sqft, model, orientation, parking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnitFull {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    unitNumber: ").append(toIndentedString(unitNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    bed: ").append(toIndentedString(bed)).append("\n");
    sb.append("    bath: ").append(toIndentedString(bath)).append("\n");
    sb.append("    sqft: ").append(toIndentedString(sqft)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    orientation: ").append(toIndentedString(orientation)).append("\n");
    sb.append("    parking: ").append(toIndentedString(parking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `_id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%s_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `floor` to the URL query string
    if (getFloor() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfloor%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFloor()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `unitNumber` to the URL query string
    if (getUnitNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sunitNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnitNumber()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `price` to the URL query string
    if (getPrice() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrice()))));
    }

    // add `bed` to the URL query string
    if (getBed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBed()))));
    }

    // add `bath` to the URL query string
    if (getBath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBath()))));
    }

    // add `sqft` to the URL query string
    if (getSqft() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssqft%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSqft()))));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
    }

    // add `orientation` to the URL query string
    if (getOrientation() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sorientation%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrientation()))));
    }

    // add `parking` to the URL query string
    if (getParking() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparking%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParking()))));
    }

    return joiner.toString();
  }
}

