/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthResponse
 */
class AuthResponseTest {
    private final AuthResponse model = new AuthResponse();

    /**
     * Model tests for AuthResponse
     */
    @Test
    void testAuthResponse() {
        // TODO: test AuthResponse
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'accessToken'
     */
    @Test
    void accessTokenTest() {
        // TODO: test accessToken
    }

}
