/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateGroupBody
 */
class CreateGroupBodyTest {
    private final CreateGroupBody model = new CreateGroupBody();

    /**
     * Model tests for CreateGroupBody
     */
    @Test
    void testCreateGroupBody() {
        // TODO: test CreateGroupBody
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'hostName'
     */
    @Test
    void hostNameTest() {
        // TODO: test hostName
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'propertyType'
     */
    @Test
    void propertyTypeTest() {
        // TODO: test propertyType
    }

}
