/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FloorFull
 */
class FloorFullTest {
    private final FloorFull model = new FloorFull();

    /**
     * Model tests for FloorFull
     */
    @Test
    void testFloorFull() {
        // TODO: test FloorFull
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'project'
     */
    @Test
    void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'level'
     */
    @Test
    void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'position'
     */
    @Test
    void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'path'
     */
    @Test
    void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'alternativePaths'
     */
    @Test
    void alternativePathsTest() {
        // TODO: test alternativePaths
    }

    /**
     * Test the property 'image'
     */
    @Test
    void imageTest() {
        // TODO: test image
    }

}
