/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.GroupProjectsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Group
 */
class GroupTest {
    private final Group model = new Group();

    /**
     * Model tests for Group
     */
    @Test
    void testGroup() {
        // TODO: test Group
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'hostName'
     */
    @Test
    void hostNameTest() {
        // TODO: test hostName
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'propertyType'
     */
    @Test
    void propertyTypeTest() {
        // TODO: test propertyType
    }

    /**
     * Test the property 'user'
     */
    @Test
    void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'projects'
     */
    @Test
    void projectsTest() {
        // TODO: test projects
    }

    /**
     * Test the property 'isOwner'
     */
    @Test
    void isOwnerTest() {
        // TODO: test isOwner
    }

    /**
     * Test the property 'isAdmin'
     */
    @Test
    void isAdminTest() {
        // TODO: test isAdmin
    }

    /**
     * Test the property 'isEditor'
     */
    @Test
    void isEditorTest() {
        // TODO: test isEditor
    }

}
