/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoginBody
 */
class LoginBodyTest {
    private final LoginBody model = new LoginBody();

    /**
     * Model tests for LoginBody
     */
    @Test
    void testLoginBody() {
        // TODO: test LoginBody
    }

    /**
     * Test the property 'username'
     */
    @Test
    void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'impersonate'
     */
    @Test
    void impersonateTest() {
        // TODO: test impersonate
    }

}
