/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectCustomButtonTxt
 */
class ProjectCustomButtonTxtTest {
    private final ProjectCustomButtonTxt model = new ProjectCustomButtonTxt();

    /**
     * Model tests for ProjectCustomButtonTxt
     */
    @Test
    void testProjectCustomButtonTxt() {
        // TODO: test ProjectCustomButtonTxt
    }

    /**
     * Test the property 'en'
     */
    @Test
    void enTest() {
        // TODO: test en
    }

    /**
     * Test the property 'fr'
     */
    @Test
    void frTest() {
        // TODO: test fr
    }

    /**
     * Test the property 'de'
     */
    @Test
    void deTest() {
        // TODO: test de
    }

    /**
     * Test the property 'es'
     */
    @Test
    void esTest() {
        // TODO: test es
    }

    /**
     * Test the property 'zh'
     */
    @Test
    void zhTest() {
        // TODO: test zh
    }

}
