/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.Collection;
import io.planpoint.model.CommercialSpace;
import io.planpoint.model.Floor;
import io.planpoint.model.ProjectCustomButtonTxt;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Project
 */
class ProjectTest {
    private final Project model = new Project();

    /**
     * Model tests for Project
     */
    @Test
    void testProject() {
        // TODO: test Project
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'hostName'
     */
    @Test
    void hostNameTest() {
        // TODO: test hostName
    }

    /**
     * Test the property 'floors'
     */
    @Test
    void floorsTest() {
        // TODO: test floors
    }

    /**
     * Test the property 'commercialSpaces'
     */
    @Test
    void commercialSpacesTest() {
        // TODO: test commercialSpaces
    }

    /**
     * Test the property 'collections'
     */
    @Test
    void collectionsTest() {
        // TODO: test collections
    }

    /**
     * Test the property 'projectLang'
     */
    @Test
    void projectLangTest() {
        // TODO: test projectLang
    }

    /**
     * Test the property 'styleNavigation'
     */
    @Test
    void styleNavigationTest() {
        // TODO: test styleNavigation
    }

    /**
     * Test the property 'showPrices'
     */
    @Test
    void showPricesTest() {
        // TODO: test showPrices
    }

    /**
     * Test the property 'showAvailability'
     */
    @Test
    void showAvailabilityTest() {
        // TODO: test showAvailability
    }

    /**
     * Test the property 'showBathrooms'
     */
    @Test
    void showBathroomsTest() {
        // TODO: test showBathrooms
    }

    /**
     * Test the property 'showParking'
     */
    @Test
    void showParkingTest() {
        // TODO: test showParking
    }

    /**
     * Test the property 'showOrientation'
     */
    @Test
    void showOrientationTest() {
        // TODO: test showOrientation
    }

    /**
     * Test the property 'hideSold'
     */
    @Test
    void hideSoldTest() {
        // TODO: test hideSold
    }

    /**
     * Test the property 'initialView'
     */
    @Test
    void initialViewTest() {
        // TODO: test initialView
    }

    /**
     * Test the property 'logo'
     */
    @Test
    void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'coverImage'
     */
    @Test
    void coverImageTest() {
        // TODO: test coverImage
    }

    /**
     * Test the property 'colorBase'
     */
    @Test
    void colorBaseTest() {
        // TODO: test colorBase
    }

    /**
     * Test the property 'colorAccent'
     */
    @Test
    void colorAccentTest() {
        // TODO: test colorAccent
    }

    /**
     * Test the property 'colorButton'
     */
    @Test
    void colorButtonTest() {
        // TODO: test colorButton
    }

    /**
     * Test the property 'colorAvailable'
     */
    @Test
    void colorAvailableTest() {
        // TODO: test colorAvailable
    }

    /**
     * Test the property 'colorSold'
     */
    @Test
    void colorSoldTest() {
        // TODO: test colorSold
    }

    /**
     * Test the property 'colorReserved'
     */
    @Test
    void colorReservedTest() {
        // TODO: test colorReserved
    }

    /**
     * Test the property 'customButtonTxt'
     */
    @Test
    void customButtonTxtTest() {
        // TODO: test customButtonTxt
    }

    /**
     * Test the property 'internalURLs'
     */
    @Test
    void internalURLsTest() {
        // TODO: test internalURLs
    }

    /**
     * Test the property 'websiteURL'
     */
    @Test
    void websiteURLTest() {
        // TODO: test websiteURL
    }

    /**
     * Test the property 'customDomain'
     */
    @Test
    void customDomainTest() {
        // TODO: test customDomain
    }

    /**
     * Test the property 'sharePageEnabled'
     */
    @Test
    void sharePageEnabledTest() {
        // TODO: test sharePageEnabled
    }

}
