/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.ErrorResponsePaused;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectSummary
 */
class ProjectSummaryTest {
    private final ProjectSummary model = new ProjectSummary();

    /**
     * Model tests for ProjectSummary
     */
    @Test
    void testProjectSummary() {
        // TODO: test ProjectSummary
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'hostName'
     */
    @Test
    void hostNameTest() {
        // TODO: test hostName
    }

    /**
     * Test the property 'projectType'
     */
    @Test
    void projectTypeTest() {
        // TODO: test projectType
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusOverride'
     */
    @Test
    void statusOverrideTest() {
        // TODO: test statusOverride
    }

    /**
     * Test the property 'paused'
     */
    @Test
    void pausedTest() {
        // TODO: test paused
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
