/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.UnitFull;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UnitsListResponse
 */
class UnitsListResponseTest {
    private final UnitsListResponse model = new UnitsListResponse();

    /**
     * Model tests for UnitsListResponse
     */
    @Test
    void testUnitsListResponse() {
        // TODO: test UnitsListResponse
    }

    /**
     * Test the property 'records'
     */
    @Test
    void recordsTest() {
        // TODO: test records
    }

    /**
     * Test the property 'count'
     */
    @Test
    void countTest() {
        // TODO: test count
    }

}
