/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.planpoint.model.UnitModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Unit
 */
class UnitTest {
    private final Unit model = new Unit();

    /**
     * Model tests for Unit
     */
    @Test
    void testUnit() {
        // TODO: test Unit
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'unitNumber'
     */
    @Test
    void unitNumberTest() {
        // TODO: test unitNumber
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'bed'
     */
    @Test
    void bedTest() {
        // TODO: test bed
    }

    /**
     * Test the property 'bath'
     */
    @Test
    void bathTest() {
        // TODO: test bath
    }

    /**
     * Test the property 'sqft'
     */
    @Test
    void sqftTest() {
        // TODO: test sqft
    }

    /**
     * Test the property 'model'
     */
    @Test
    void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'floor'
     */
    @Test
    void floorTest() {
        // TODO: test floor
    }

    /**
     * Test the property 'orientation'
     */
    @Test
    void orientationTest() {
        // TODO: test orientation
    }

    /**
     * Test the property 'parking'
     */
    @Test
    void parkingTest() {
        // TODO: test parking
    }

    /**
     * Test the property 'unitmodels'
     */
    @Test
    void unitmodelsTest() {
        // TODO: test unitmodels
    }

}
