/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.planpoint.api;

import io.planpoint.ApiClient;
import io.planpoint.ApiException;
import io.planpoint.ApiResponse;
import io.planpoint.Configuration;
import io.planpoint.Pair;

import io.planpoint.model.CreateFloorBody;
import io.planpoint.model.ErrorResponse;
import io.planpoint.model.FloorFull;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T18:57:29.273682275Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class FloorsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public FloorsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public FloorsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a floor
   * 
   * @param createFloorBody  (required)
   * @return FloorFull
   * @throws ApiException if fails to make API call
   */
  public FloorFull createFloor(@javax.annotation.Nonnull CreateFloorBody createFloorBody) throws ApiException {
    return createFloor(createFloorBody, null);
  }

  /**
   * Create a floor
   * 
   * @param createFloorBody  (required)
   * @param headers Optional headers to include in the request
   * @return FloorFull
   * @throws ApiException if fails to make API call
   */
  public FloorFull createFloor(@javax.annotation.Nonnull CreateFloorBody createFloorBody, Map<String, String> headers) throws ApiException {
    ApiResponse<FloorFull> localVarResponse = createFloorWithHttpInfo(createFloorBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a floor
   * 
   * @param createFloorBody  (required)
   * @return ApiResponse&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FloorFull> createFloorWithHttpInfo(@javax.annotation.Nonnull CreateFloorBody createFloorBody) throws ApiException {
    return createFloorWithHttpInfo(createFloorBody, null);
  }

  /**
   * Create a floor
   * 
   * @param createFloorBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FloorFull> createFloorWithHttpInfo(@javax.annotation.Nonnull CreateFloorBody createFloorBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createFloorRequestBuilder(createFloorBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createFloor", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<FloorFull>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        FloorFull responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<FloorFull>() {});
        

        return new ApiResponse<FloorFull>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createFloorRequestBuilder(@javax.annotation.Nonnull CreateFloorBody createFloorBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createFloorBody' is set
    if (createFloorBody == null) {
      throw new ApiException(400, "Missing the required parameter 'createFloorBody' when calling createFloor");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/floors";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createFloorBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a floor by ID
   * 
   * @param id  (required)
   * @return FloorFull
   * @throws ApiException if fails to make API call
   */
  public FloorFull getFloor(@javax.annotation.Nonnull String id) throws ApiException {
    return getFloor(id, null);
  }

  /**
   * Get a floor by ID
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return FloorFull
   * @throws ApiException if fails to make API call
   */
  public FloorFull getFloor(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<FloorFull> localVarResponse = getFloorWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a floor by ID
   * 
   * @param id  (required)
   * @return ApiResponse&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FloorFull> getFloorWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getFloorWithHttpInfo(id, null);
  }

  /**
   * Get a floor by ID
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FloorFull> getFloorWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getFloorRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getFloor", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<FloorFull>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        FloorFull responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<FloorFull>() {});
        

        return new ApiResponse<FloorFull>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getFloorRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getFloor");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/floors/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get floors for a project
   * 
   * @param pid  (required)
   * @return List&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public List<FloorFull> getFloors(@javax.annotation.Nonnull String pid) throws ApiException {
    return getFloors(pid, null);
  }

  /**
   * Get floors for a project
   * 
   * @param pid  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public List<FloorFull> getFloors(@javax.annotation.Nonnull String pid, Map<String, String> headers) throws ApiException {
    ApiResponse<List<FloorFull>> localVarResponse = getFloorsWithHttpInfo(pid, headers);
    return localVarResponse.getData();
  }

  /**
   * Get floors for a project
   * 
   * @param pid  (required)
   * @return ApiResponse&lt;List&lt;FloorFull&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<FloorFull>> getFloorsWithHttpInfo(@javax.annotation.Nonnull String pid) throws ApiException {
    return getFloorsWithHttpInfo(pid, null);
  }

  /**
   * Get floors for a project
   * 
   * @param pid  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;FloorFull&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<FloorFull>> getFloorsWithHttpInfo(@javax.annotation.Nonnull String pid, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getFloorsRequestBuilder(pid, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getFloors", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<FloorFull>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<FloorFull> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<FloorFull>>() {});
        

        return new ApiResponse<List<FloorFull>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getFloorsRequestBuilder(@javax.annotation.Nonnull String pid, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'pid' is set
    if (pid == null) {
      throw new ApiException(400, "Missing the required parameter 'pid' when calling getFloors");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/floors";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "pid";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("pid", pid));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a floor
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @return FloorFull
   * @throws ApiException if fails to make API call
   */
  public FloorFull updateFloor(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody) throws ApiException {
    return updateFloor(id, requestBody, null);
  }

  /**
   * Update a floor
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return FloorFull
   * @throws ApiException if fails to make API call
   */
  public FloorFull updateFloor(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody, Map<String, String> headers) throws ApiException {
    ApiResponse<FloorFull> localVarResponse = updateFloorWithHttpInfo(id, requestBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Update a floor
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @return ApiResponse&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FloorFull> updateFloorWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody) throws ApiException {
    return updateFloorWithHttpInfo(id, requestBody, null);
  }

  /**
   * Update a floor
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;FloorFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<FloorFull> updateFloorWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateFloorRequestBuilder(id, requestBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateFloor", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<FloorFull>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        FloorFull responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<FloorFull>() {});
        

        return new ApiResponse<FloorFull>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateFloorRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateFloor");
    }
    // verify the required parameter 'requestBody' is set
    if (requestBody == null) {
      throw new ApiException(400, "Missing the required parameter 'requestBody' when calling updateFloor");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/floors/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestBody);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
