/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.planpoint.api;

import io.planpoint.ApiClient;
import io.planpoint.ApiException;
import io.planpoint.ApiResponse;
import io.planpoint.Configuration;
import io.planpoint.Pair;

import io.planpoint.model.BatchUpdateUnitsBody;
import io.planpoint.model.CreateUnitBody;
import io.planpoint.model.ErrorResponse;
import io.planpoint.model.UnitFull;
import io.planpoint.model.UnitsListResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-18T18:57:29.273682275Z[Etc/UTC]", comments = "Generator version: 7.21.0")
public class UnitsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public UnitsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public UnitsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Batch update units
   * 
   * @param batchUpdateUnitsBody  (required)
   * @return List&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UnitFull> batchUpdateUnits(@javax.annotation.Nonnull BatchUpdateUnitsBody batchUpdateUnitsBody) throws ApiException {
    return batchUpdateUnits(batchUpdateUnitsBody, null);
  }

  /**
   * Batch update units
   * 
   * @param batchUpdateUnitsBody  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public List<UnitFull> batchUpdateUnits(@javax.annotation.Nonnull BatchUpdateUnitsBody batchUpdateUnitsBody, Map<String, String> headers) throws ApiException {
    ApiResponse<List<UnitFull>> localVarResponse = batchUpdateUnitsWithHttpInfo(batchUpdateUnitsBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Batch update units
   * 
   * @param batchUpdateUnitsBody  (required)
   * @return ApiResponse&lt;List&lt;UnitFull&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UnitFull>> batchUpdateUnitsWithHttpInfo(@javax.annotation.Nonnull BatchUpdateUnitsBody batchUpdateUnitsBody) throws ApiException {
    return batchUpdateUnitsWithHttpInfo(batchUpdateUnitsBody, null);
  }

  /**
   * Batch update units
   * 
   * @param batchUpdateUnitsBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;UnitFull&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<UnitFull>> batchUpdateUnitsWithHttpInfo(@javax.annotation.Nonnull BatchUpdateUnitsBody batchUpdateUnitsBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = batchUpdateUnitsRequestBuilder(batchUpdateUnitsBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("batchUpdateUnits", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<UnitFull>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<UnitFull> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<UnitFull>>() {});
        

        return new ApiResponse<List<UnitFull>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder batchUpdateUnitsRequestBuilder(@javax.annotation.Nonnull BatchUpdateUnitsBody batchUpdateUnitsBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'batchUpdateUnitsBody' is set
    if (batchUpdateUnitsBody == null) {
      throw new ApiException(400, "Missing the required parameter 'batchUpdateUnitsBody' when calling batchUpdateUnits");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/units";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(batchUpdateUnitsBody);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create a unit
   * 
   * @param createUnitBody  (required)
   * @return UnitFull
   * @throws ApiException if fails to make API call
   */
  public UnitFull createUnit(@javax.annotation.Nonnull CreateUnitBody createUnitBody) throws ApiException {
    return createUnit(createUnitBody, null);
  }

  /**
   * Create a unit
   * 
   * @param createUnitBody  (required)
   * @param headers Optional headers to include in the request
   * @return UnitFull
   * @throws ApiException if fails to make API call
   */
  public UnitFull createUnit(@javax.annotation.Nonnull CreateUnitBody createUnitBody, Map<String, String> headers) throws ApiException {
    ApiResponse<UnitFull> localVarResponse = createUnitWithHttpInfo(createUnitBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a unit
   * 
   * @param createUnitBody  (required)
   * @return ApiResponse&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitFull> createUnitWithHttpInfo(@javax.annotation.Nonnull CreateUnitBody createUnitBody) throws ApiException {
    return createUnitWithHttpInfo(createUnitBody, null);
  }

  /**
   * Create a unit
   * 
   * @param createUnitBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitFull> createUnitWithHttpInfo(@javax.annotation.Nonnull CreateUnitBody createUnitBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createUnitRequestBuilder(createUnitBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createUnit", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UnitFull>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UnitFull responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UnitFull>() {});
        

        return new ApiResponse<UnitFull>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createUnitRequestBuilder(@javax.annotation.Nonnull CreateUnitBody createUnitBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createUnitBody' is set
    if (createUnitBody == null) {
      throw new ApiException(400, "Missing the required parameter 'createUnitBody' when calling createUnit");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/units";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createUnitBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a unit
   * 
   * @param id  (required)
   * @return ErrorResponse
   * @throws ApiException if fails to make API call
   */
  public ErrorResponse deleteUnit(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteUnit(id, null);
  }

  /**
   * Delete a unit
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ErrorResponse
   * @throws ApiException if fails to make API call
   */
  public ErrorResponse deleteUnit(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<ErrorResponse> localVarResponse = deleteUnitWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete a unit
   * 
   * @param id  (required)
   * @return ApiResponse&lt;ErrorResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ErrorResponse> deleteUnitWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return deleteUnitWithHttpInfo(id, null);
  }

  /**
   * Delete a unit
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ErrorResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ErrorResponse> deleteUnitWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteUnitRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteUnit", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ErrorResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ErrorResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ErrorResponse>() {});
        

        return new ApiResponse<ErrorResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteUnitRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteUnit");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/units/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a unit by ID
   * 
   * @param id  (required)
   * @return UnitFull
   * @throws ApiException if fails to make API call
   */
  public UnitFull getUnit(@javax.annotation.Nonnull String id) throws ApiException {
    return getUnit(id, null);
  }

  /**
   * Get a unit by ID
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return UnitFull
   * @throws ApiException if fails to make API call
   */
  public UnitFull getUnit(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    ApiResponse<UnitFull> localVarResponse = getUnitWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a unit by ID
   * 
   * @param id  (required)
   * @return ApiResponse&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitFull> getUnitWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return getUnitWithHttpInfo(id, null);
  }

  /**
   * Get a unit by ID
   * 
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitFull> getUnitWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUnitRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUnit", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UnitFull>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UnitFull responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UnitFull>() {});
        

        return new ApiResponse<UnitFull>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUnitRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getUnit");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/units/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get units for a project
   * 
   * @param pid  (required)
   * @return UnitsListResponse
   * @throws ApiException if fails to make API call
   */
  public UnitsListResponse getUnits(@javax.annotation.Nonnull String pid) throws ApiException {
    return getUnits(pid, null);
  }

  /**
   * Get units for a project
   * 
   * @param pid  (required)
   * @param headers Optional headers to include in the request
   * @return UnitsListResponse
   * @throws ApiException if fails to make API call
   */
  public UnitsListResponse getUnits(@javax.annotation.Nonnull String pid, Map<String, String> headers) throws ApiException {
    ApiResponse<UnitsListResponse> localVarResponse = getUnitsWithHttpInfo(pid, headers);
    return localVarResponse.getData();
  }

  /**
   * Get units for a project
   * 
   * @param pid  (required)
   * @return ApiResponse&lt;UnitsListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitsListResponse> getUnitsWithHttpInfo(@javax.annotation.Nonnull String pid) throws ApiException {
    return getUnitsWithHttpInfo(pid, null);
  }

  /**
   * Get units for a project
   * 
   * @param pid  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UnitsListResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitsListResponse> getUnitsWithHttpInfo(@javax.annotation.Nonnull String pid, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUnitsRequestBuilder(pid, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUnits", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UnitsListResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UnitsListResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UnitsListResponse>() {});
        

        return new ApiResponse<UnitsListResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUnitsRequestBuilder(@javax.annotation.Nonnull String pid, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'pid' is set
    if (pid == null) {
      throw new ApiException(400, "Missing the required parameter 'pid' when calling getUnits");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/units";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "pid";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("pid", pid));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a unit
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @return UnitFull
   * @throws ApiException if fails to make API call
   */
  public UnitFull updateUnit(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody) throws ApiException {
    return updateUnit(id, requestBody, null);
  }

  /**
   * Update a unit
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return UnitFull
   * @throws ApiException if fails to make API call
   */
  public UnitFull updateUnit(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody, Map<String, String> headers) throws ApiException {
    ApiResponse<UnitFull> localVarResponse = updateUnitWithHttpInfo(id, requestBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Update a unit
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @return ApiResponse&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitFull> updateUnitWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody) throws ApiException {
    return updateUnitWithHttpInfo(id, requestBody, null);
  }

  /**
   * Update a unit
   * 
   * @param id  (required)
   * @param requestBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UnitFull&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnitFull> updateUnitWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateUnitRequestBuilder(id, requestBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateUnit", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UnitFull>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UnitFull responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UnitFull>() {});
        

        return new ApiResponse<UnitFull>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateUnitRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull Map<String, Object> requestBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateUnit");
    }
    // verify the required parameter 'requestBody' is set
    if (requestBody == null) {
      throw new ApiException(400, "Missing the required parameter 'requestBody' when calling updateUnit");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/units/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestBody);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
