/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.api;

import io.planpoint.ApiException;
import io.planpoint.model.CreateFloorBody;
import io.planpoint.model.ErrorResponse;
import io.planpoint.model.FloorFull;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for FloorsApi
 */
@Disabled
public class FloorsApiTest {

    private final FloorsApi api = new FloorsApi();

    
    /**
     * Create a floor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFloorTest() throws ApiException {
        CreateFloorBody createFloorBody = null;
        FloorFull response = 
        api.createFloor(createFloorBody);
        
        // TODO: test validations
    }
    
    /**
     * Get a floor by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFloorTest() throws ApiException {
        String id = null;
        FloorFull response = 
        api.getFloor(id);
        
        // TODO: test validations
    }
    
    /**
     * Get floors for a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFloorsTest() throws ApiException {
        String pid = null;
        List<FloorFull> response = 
        api.getFloors(pid);
        
        // TODO: test validations
    }
    
    /**
     * Update a floor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFloorTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        FloorFull response = 
        api.updateFloor(id, requestBody);
        
        // TODO: test validations
    }
    
}
