/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.api;

import io.planpoint.ApiException;
import io.planpoint.model.ErrorResponse;
import io.planpoint.model.Lead;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for LeadsApi
 */
@Disabled
public class LeadsApiTest {

    private final LeadsApi api = new LeadsApi();

    
    /**
     * Get leads for a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLeadsTest() throws ApiException {
        String pid = null;
        List<Lead> response = 
        api.getLeads(pid);
        
        // TODO: test validations
    }
    
}
