/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.api;

import io.planpoint.ApiException;
import io.planpoint.model.ErrorResponse;
import io.planpoint.model.FindProjectBody;
import io.planpoint.model.Project;
import io.planpoint.model.ProjectSummary;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ProjectsApi
 */
@Disabled
public class ProjectsApiTest {

    private final ProjectsApi api = new ProjectsApi();

    
    /**
     * Find a project by namespace and hostname
     *
     * Returns the full project document including floors, units, commercial spaces, and collections.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findProjectTest() throws ApiException {
        FindProjectBody findProjectBody = null;
        Project response = 
        api.findProject(findProjectBody);
        
        // TODO: test validations
    }
    
    /**
     * Get my projects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMyProjectsTest() throws ApiException {
        List<ProjectSummary> response = 
        api.getMyProjects();
        
        // TODO: test validations
    }
    
    /**
     * Get a project by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectTest() throws ApiException {
        String id = null;
        Project response = 
        api.getProject(id);
        
        // TODO: test validations
    }
    
    /**
     * Update a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProjectTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        Project response = 
        api.updateProject(id, requestBody);
        
        // TODO: test validations
    }
    
}
