/*
 * PlanPoint API
 * REST API for the PlanPoint real estate sales and marketing platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.planpoint.api;

import io.planpoint.ApiException;
import io.planpoint.model.BatchUpdateUnitsBody;
import io.planpoint.model.CreateUnitBody;
import io.planpoint.model.ErrorResponse;
import io.planpoint.model.UnitFull;
import io.planpoint.model.UnitsListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for UnitsApi
 */
@Disabled
public class UnitsApiTest {

    private final UnitsApi api = new UnitsApi();

    
    /**
     * Batch update units
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void batchUpdateUnitsTest() throws ApiException {
        BatchUpdateUnitsBody batchUpdateUnitsBody = null;
        List<UnitFull> response = 
        api.batchUpdateUnits(batchUpdateUnitsBody);
        
        // TODO: test validations
    }
    
    /**
     * Create a unit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUnitTest() throws ApiException {
        CreateUnitBody createUnitBody = null;
        UnitFull response = 
        api.createUnit(createUnitBody);
        
        // TODO: test validations
    }
    
    /**
     * Delete a unit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUnitTest() throws ApiException {
        String id = null;
        ErrorResponse response = 
        api.deleteUnit(id);
        
        // TODO: test validations
    }
    
    /**
     * Get a unit by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUnitTest() throws ApiException {
        String id = null;
        UnitFull response = 
        api.getUnit(id);
        
        // TODO: test validations
    }
    
    /**
     * Get units for a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUnitsTest() throws ApiException {
        String pid = null;
        UnitsListResponse response = 
        api.getUnits(pid);
        
        // TODO: test validations
    }
    
    /**
     * Update a unit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUnitTest() throws ApiException {
        String id = null;
        Map<String, Object> requestBody = null;
        UnitFull response = 
        api.updateUnit(id, requestBody);
        
        // TODO: test validations
    }
    
}
